apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses: 
      - CLUSTER_IP-CLUSTER_IP
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system