apiVersion: 1

datasources:
- name: Monitoring
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb-svc:8086
  database: telegraf
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: admin